fun main() {
    println("hotfix 4.0.9")
    println("hotfix 4.0.8")
    println("hotfix 4.0.7")
    println("hotfix 4.0.6")
    println("hotfix 4.0.5")
    println("hotfix 4.0.4")
    println("hotfix 4.0.3")
    println("hotfix 4.0.2")
    println("hotfix 4.0.1")
    println("release note4")
    println("forth")
    println("release note3")
    println("third")
    println("release note2")
    println("second")
    println("hotfix 1.0.1")
    println("release note")
    println("first")
    println("init")
}